# docker-compose -p learning_service up --build 
version: '3.8'

services:
  postgres:
    container_name: learning_service_postgres
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: learning
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  app:
    container_name: learning_service_grpc
    build:
      context: ../..
      dockerfile: Dockerfile
    ports:
      - "5152:5152"
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - ../../config/config.json:/app/config/config.json

volumes:
  postgres_data: