# docker-compose -p auth_service up --build
version: '3.8'

services:
  redis:
    container_name: auth_service_redis
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  postgres:
    container_name: auth_service_postgres
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: auth
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  app:
    container_name: auth_service_grpc
    build:
      context: ../..
      dockerfile: Dockerfile
    ports:
      - "5151:5151"
    depends_on:
      - redis
      - postgres
    restart: unless-stopped
    volumes:
      - ../../config/config.json:/app/config/config.json

volumes:
  redis_data:
  postgres_data: