// protoc --go_out=./pkg --go_opt=paths=source_relative --go-grpc_out=./pkg --go-grpc_opt=paths=source_relative ./api/grpc/v1/analytics.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: api/grpc/v1/analytics.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Analytics_GetUserRating_FullMethodName           = "/analytics.v1.analytics/GetUserRating"
	Analytics_GetUserRatingInCourse_FullMethodName   = "/analytics.v1.analytics/GetUserRatingInCourse"
	Analytics_GetUserProgressInCourse_FullMethodName = "/analytics.v1.analytics/GetUserProgressInCourse"
)

// AnalyticsClient is the client API for Analytics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AnalyticsClient interface {
	GetUserRating(ctx context.Context, in *GetUserRatingRequest, opts ...grpc.CallOption) (*GetUserRatingResponse, error)
	GetUserRatingInCourse(ctx context.Context, in *GetUserRatingInCourseRequest, opts ...grpc.CallOption) (*GetUserRatingInCourseResponse, error)
	GetUserProgressInCourse(ctx context.Context, in *GetUserProgressInCourseRequest, opts ...grpc.CallOption) (*GetUserProgressInCourseResponse, error)
}

type analyticsClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsClient(cc grpc.ClientConnInterface) AnalyticsClient {
	return &analyticsClient{cc}
}

func (c *analyticsClient) GetUserRating(ctx context.Context, in *GetUserRatingRequest, opts ...grpc.CallOption) (*GetUserRatingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserRatingResponse)
	err := c.cc.Invoke(ctx, Analytics_GetUserRating_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsClient) GetUserRatingInCourse(ctx context.Context, in *GetUserRatingInCourseRequest, opts ...grpc.CallOption) (*GetUserRatingInCourseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserRatingInCourseResponse)
	err := c.cc.Invoke(ctx, Analytics_GetUserRatingInCourse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsClient) GetUserProgressInCourse(ctx context.Context, in *GetUserProgressInCourseRequest, opts ...grpc.CallOption) (*GetUserProgressInCourseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserProgressInCourseResponse)
	err := c.cc.Invoke(ctx, Analytics_GetUserProgressInCourse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServer is the server API for Analytics service.
// All implementations must embed UnimplementedAnalyticsServer
// for forward compatibility.
type AnalyticsServer interface {
	GetUserRating(context.Context, *GetUserRatingRequest) (*GetUserRatingResponse, error)
	GetUserRatingInCourse(context.Context, *GetUserRatingInCourseRequest) (*GetUserRatingInCourseResponse, error)
	GetUserProgressInCourse(context.Context, *GetUserProgressInCourseRequest) (*GetUserProgressInCourseResponse, error)
	mustEmbedUnimplementedAnalyticsServer()
}

// UnimplementedAnalyticsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsServer struct{}

func (UnimplementedAnalyticsServer) GetUserRating(context.Context, *GetUserRatingRequest) (*GetUserRatingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserRating not implemented")
}
func (UnimplementedAnalyticsServer) GetUserRatingInCourse(context.Context, *GetUserRatingInCourseRequest) (*GetUserRatingInCourseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserRatingInCourse not implemented")
}
func (UnimplementedAnalyticsServer) GetUserProgressInCourse(context.Context, *GetUserProgressInCourseRequest) (*GetUserProgressInCourseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserProgressInCourse not implemented")
}
func (UnimplementedAnalyticsServer) mustEmbedUnimplementedAnalyticsServer() {}
func (UnimplementedAnalyticsServer) testEmbeddedByValue()                   {}

// UnsafeAnalyticsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServer will
// result in compilation errors.
type UnsafeAnalyticsServer interface {
	mustEmbedUnimplementedAnalyticsServer()
}

func RegisterAnalyticsServer(s grpc.ServiceRegistrar, srv AnalyticsServer) {
	// If the following call pancis, it indicates UnimplementedAnalyticsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Analytics_ServiceDesc, srv)
}

func _Analytics_GetUserRating_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRatingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServer).GetUserRating(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Analytics_GetUserRating_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServer).GetUserRating(ctx, req.(*GetUserRatingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Analytics_GetUserRatingInCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRatingInCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServer).GetUserRatingInCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Analytics_GetUserRatingInCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServer).GetUserRatingInCourse(ctx, req.(*GetUserRatingInCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Analytics_GetUserProgressInCourse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserProgressInCourseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServer).GetUserProgressInCourse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Analytics_GetUserProgressInCourse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServer).GetUserProgressInCourse(ctx, req.(*GetUserProgressInCourseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Analytics_ServiceDesc is the grpc.ServiceDesc for Analytics service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Analytics_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics.v1.analytics",
	HandlerType: (*AnalyticsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUserRating",
			Handler:    _Analytics_GetUserRating_Handler,
		},
		{
			MethodName: "GetUserRatingInCourse",
			Handler:    _Analytics_GetUserRatingInCourse_Handler,
		},
		{
			MethodName: "GetUserProgressInCourse",
			Handler:    _Analytics_GetUserProgressInCourse_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/grpc/v1/analytics.proto",
}
