// protoc --go_out=./pkg --go_opt=paths=source_relative --go-grpc_out=./pkg --go-grpc_opt=paths=source_relative ./api/grpc/v1/analytics.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: api/grpc/v1/analytics.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserCourseProgress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID               int64   `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	CourseID             int64   `protobuf:"varint,2,opt,name=courseID,proto3" json:"courseID,omitempty"`
	CompletionPercentage float64 `protobuf:"fixed64,3,opt,name=completionPercentage,proto3" json:"completionPercentage,omitempty"`
	LastUpdated          int64   `protobuf:"varint,4,opt,name=lastUpdated,proto3" json:"lastUpdated,omitempty"`
	CompletedLessons     int64   `protobuf:"varint,5,opt,name=completedLessons,proto3" json:"completedLessons,omitempty"`
	CompletedQuizzes     int64   `protobuf:"varint,6,opt,name=completedQuizzes,proto3" json:"completedQuizzes,omitempty"`
	CompletedTasks       int64   `protobuf:"varint,7,opt,name=completedTasks,proto3" json:"completedTasks,omitempty"`
}

func (x *UserCourseProgress) Reset() {
	*x = UserCourseProgress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_v1_analytics_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserCourseProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCourseProgress) ProtoMessage() {}

func (x *UserCourseProgress) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_analytics_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCourseProgress.ProtoReflect.Descriptor instead.
func (*UserCourseProgress) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *UserCourseProgress) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *UserCourseProgress) GetCourseID() int64 {
	if x != nil {
		return x.CourseID
	}
	return 0
}

func (x *UserCourseProgress) GetCompletionPercentage() float64 {
	if x != nil {
		return x.CompletionPercentage
	}
	return 0
}

func (x *UserCourseProgress) GetLastUpdated() int64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

func (x *UserCourseProgress) GetCompletedLessons() int64 {
	if x != nil {
		return x.CompletedLessons
	}
	return 0
}

func (x *UserCourseProgress) GetCompletedQuizzes() int64 {
	if x != nil {
		return x.CompletedQuizzes
	}
	return 0
}

func (x *UserCourseProgress) GetCompletedTasks() int64 {
	if x != nil {
		return x.CompletedTasks
	}
	return 0
}

type CourseRating struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID      int64   `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	CourseID    int64   `protobuf:"varint,2,opt,name=courseID,proto3" json:"courseID,omitempty"`
	Rating      float64 `protobuf:"fixed64,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Position    int64   `protobuf:"varint,4,opt,name=position,proto3" json:"position,omitempty"`
	LastUpdated int64   `protobuf:"varint,5,opt,name=lastUpdated,proto3" json:"lastUpdated,omitempty"`
}

func (x *CourseRating) Reset() {
	*x = CourseRating{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_v1_analytics_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CourseRating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseRating) ProtoMessage() {}

func (x *CourseRating) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_analytics_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseRating.ProtoReflect.Descriptor instead.
func (*CourseRating) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *CourseRating) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *CourseRating) GetCourseID() int64 {
	if x != nil {
		return x.CourseID
	}
	return 0
}

func (x *CourseRating) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *CourseRating) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *CourseRating) GetLastUpdated() int64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

type GlobalRating struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID      int64   `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Rating      float64 `protobuf:"fixed64,2,opt,name=rating,proto3" json:"rating,omitempty"`
	Position    int64   `protobuf:"varint,3,opt,name=position,proto3" json:"position,omitempty"`
	LastUpdated int64   `protobuf:"varint,4,opt,name=lastUpdated,proto3" json:"lastUpdated,omitempty"`
}

func (x *GlobalRating) Reset() {
	*x = GlobalRating{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_v1_analytics_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalRating) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalRating) ProtoMessage() {}

func (x *GlobalRating) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_analytics_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalRating.ProtoReflect.Descriptor instead.
func (*GlobalRating) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *GlobalRating) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *GlobalRating) GetRating() float64 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *GlobalRating) GetPosition() int64 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *GlobalRating) GetLastUpdated() int64 {
	if x != nil {
		return x.LastUpdated
	}
	return 0
}

type GetUserStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID int64 `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *GetUserStatsRequest) Reset() {
	*x = GetUserStatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_v1_analytics_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatsRequest) ProtoMessage() {}

func (x *GetUserStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_analytics_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatsRequest.ProtoReflect.Descriptor instead.
func (*GetUserStatsRequest) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserStatsRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type GetUserStatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Progress     *UserCourseProgress `protobuf:"bytes,1,opt,name=progress,proto3" json:"progress,omitempty"`
	CourseRating *CourseRating       `protobuf:"bytes,2,opt,name=courseRating,proto3" json:"courseRating,omitempty"`
	Rating       *GlobalRating       `protobuf:"bytes,3,opt,name=rating,proto3" json:"rating,omitempty"`
}

func (x *GetUserStatsResponse) Reset() {
	*x = GetUserStatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_v1_analytics_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserStatsResponse) ProtoMessage() {}

func (x *GetUserStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_v1_analytics_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserStatsResponse.ProtoReflect.Descriptor instead.
func (*GetUserStatsResponse) Descriptor() ([]byte, []int) {
	return file_api_grpc_v1_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserStatsResponse) GetProgress() *UserCourseProgress {
	if x != nil {
		return x.Progress
	}
	return nil
}

func (x *GetUserStatsResponse) GetCourseRating() *CourseRating {
	if x != nil {
		return x.CourseRating
	}
	return nil
}

func (x *GetUserStatsResponse) GetRating() *GlobalRating {
	if x != nil {
		return x.Rating
	}
	return nil
}

var File_api_grpc_v1_analytics_proto protoreflect.FileDescriptor

var file_api_grpc_v1_analytics_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x6e,
	0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61,
	0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x9e, 0x02, 0x0a, 0x12,
	0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f,
	0x75, 0x72, 0x73, 0x65, 0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x6f,
	0x75, 0x72, 0x73, 0x65, 0x49, 0x44, 0x12, 0x32, 0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65,
	0x74, 0x69, 0x6f, 0x6e, 0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x14, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e,
	0x50, 0x65, 0x72, 0x63, 0x65, 0x6e, 0x74, 0x61, 0x67, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x61,
	0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0b, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x12, 0x2a, 0x0a, 0x10,
	0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x73,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x4c, 0x65, 0x73, 0x73, 0x6f, 0x6e, 0x73, 0x12, 0x2a, 0x0a, 0x10, 0x63, 0x6f, 0x6d, 0x70,
	0x6c, 0x65, 0x74, 0x65, 0x64, 0x51, 0x75, 0x69, 0x7a, 0x7a, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x10, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x51, 0x75, 0x69,
	0x7a, 0x7a, 0x65, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65,
	0x64, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x63, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x54, 0x61, 0x73, 0x6b, 0x73, 0x22, 0x98, 0x01, 0x0a,
	0x0c, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x49,
	0x44, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x01, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x22, 0x7c, 0x0a, 0x0c, 0x47, 0x6c, 0x6f, 0x62, 0x61,
	0x6c, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x6c, 0x61, 0x73, 0x74, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x22, 0x2d, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x44, 0x22, 0xc8, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a,
	0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x55,
	0x73, 0x65, 0x72, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x50, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73,
	0x73, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x67, 0x72, 0x65, 0x73, 0x73, 0x12, 0x3e, 0x0a, 0x0c, 0x63,
	0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x43, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x0c, 0x63,
	0x6f, 0x75, 0x72, 0x73, 0x65, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x12, 0x32, 0x0a, 0x06, 0x72,
	0x61, 0x74, 0x69, 0x6e, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x6e,
	0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x6c, 0x6f, 0x62, 0x61,
	0x6c, 0x52, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x52, 0x06, 0x72, 0x61, 0x74, 0x69, 0x6e, 0x67, 0x32,
	0x62, 0x0a, 0x09, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x12, 0x55, 0x0a, 0x0c,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x21, 0x2e, 0x61,
	0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x22, 0x2e, 0x61, 0x6e, 0x61, 0x6c, 0x79, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x42, 0x15, 0x5a, 0x13, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x61, 0x6c, 0x79,
	0x74, 0x69, 0x63, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_api_grpc_v1_analytics_proto_rawDescOnce sync.Once
	file_api_grpc_v1_analytics_proto_rawDescData = file_api_grpc_v1_analytics_proto_rawDesc
)

func file_api_grpc_v1_analytics_proto_rawDescGZIP() []byte {
	file_api_grpc_v1_analytics_proto_rawDescOnce.Do(func() {
		file_api_grpc_v1_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_grpc_v1_analytics_proto_rawDescData)
	})
	return file_api_grpc_v1_analytics_proto_rawDescData
}

var file_api_grpc_v1_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_grpc_v1_analytics_proto_goTypes = []any{
	(*UserCourseProgress)(nil),   // 0: analytics.v1.UserCourseProgress
	(*CourseRating)(nil),         // 1: analytics.v1.CourseRating
	(*GlobalRating)(nil),         // 2: analytics.v1.GlobalRating
	(*GetUserStatsRequest)(nil),  // 3: analytics.v1.GetUserStatsRequest
	(*GetUserStatsResponse)(nil), // 4: analytics.v1.GetUserStatsResponse
}
var file_api_grpc_v1_analytics_proto_depIdxs = []int32{
	0, // 0: analytics.v1.GetUserStatsResponse.progress:type_name -> analytics.v1.UserCourseProgress
	1, // 1: analytics.v1.GetUserStatsResponse.courseRating:type_name -> analytics.v1.CourseRating
	2, // 2: analytics.v1.GetUserStatsResponse.rating:type_name -> analytics.v1.GlobalRating
	3, // 3: analytics.v1.analytics.GetUserStats:input_type -> analytics.v1.GetUserStatsRequest
	4, // 4: analytics.v1.analytics.GetUserStats:output_type -> analytics.v1.GetUserStatsResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_grpc_v1_analytics_proto_init() }
func file_api_grpc_v1_analytics_proto_init() {
	if File_api_grpc_v1_analytics_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_grpc_v1_analytics_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*UserCourseProgress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_v1_analytics_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CourseRating); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_v1_analytics_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*GlobalRating); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_v1_analytics_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserStatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_v1_analytics_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*GetUserStatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_grpc_v1_analytics_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_v1_analytics_proto_goTypes,
		DependencyIndexes: file_api_grpc_v1_analytics_proto_depIdxs,
		MessageInfos:      file_api_grpc_v1_analytics_proto_msgTypes,
	}.Build()
	File_api_grpc_v1_analytics_proto = out.File
	file_api_grpc_v1_analytics_proto_rawDesc = nil
	file_api_grpc_v1_analytics_proto_goTypes = nil
	file_api_grpc_v1_analytics_proto_depIdxs = nil
}
